/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.1.112 */
/* Module Version: 5.7 */
/* Thu Aug 02 20:02:46 2018 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ));
