/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.1.112 */
/* Module Version: 5.7 */
/* Fri Jul 27 20:00:03 2018 */

/* parameterized module instance */
usb3_core_pll __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), .CLKOS3( ));
